enabled: false
spawnrate: 100
votereward: false
redstonemode: false
loottable:
  enabled: false
  chance: 0.5
itemlore:
  - '§aThe fireworks can be placed'
  - '§aand lit with a flint and steel'
itemlorebangsnap:
  - '§aThrow them on the floor for fun'