name: FancyFirework
version: '${project.version}'
main: de.fanta.fancyfirework.FancyFirework
api-version: 1.18
author: ${project.author}
website: cubeside.de
softdepend: [Votifier, TreasureChest, PlayerUUIDCache, VanishNoPacket]
commands:
  fancyfirework:
    aliases: ff
    description: FancyFireWork Command
